<a href="https://colab.research.google.com/github/deepgohil/D-Science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.ndim

1

In [6]:
arr=np.array([1,2,3,4,5,6,7],"uint64")

In [7]:
arr.dtype
#data type of array

dtype('uint64')

In [8]:
arr=np.ones(10000,dtype="uint64")

In [9]:
lst = [1]*10000

#time


In [10]:
%timeit sum(lst)

10000 loops, best of 5: 74 µs per loop


In [11]:
%timeit arr.sum()

The slowest run took 9.85 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 9.78 µs per loop


In [12]:
%timeit sum(arr)
#python no function call

100 loops, best of 5: 2.31 ms per loop


slicing


In [13]:
arr = np.arange(5,25,2)

In [14]:
print(arr)
arr[2:5]

[ 5  7  9 11 13 15 17 19 21 23]


array([ 9, 11, 13])

In [15]:
lst = [1,2,3,4,5]
lst2 = lst[2:4]
print(lst)
print(lst2)
lst2[0] = 1000
print(lst)
print(lst2)

[1, 2, 3, 4, 5]
[3, 4]
[1, 2, 3, 4, 5]
[1000, 4]


In [16]:
arr = np.array([1,2,3,4,5])
arr2 = arr[2:4]
print(arr)
print(arr2)
arr2[0] = 1000
print(arr)
print(arr2)

[1 2 3 4 5]
[3 4]
[   1    2 1000    4    5]
[1000    4]


copy create aa rite karai->


In [17]:
arr = np.array([1,2,3,4,5])
arr2 = arr[2:4].copy()
print(arr)
print(arr2)
arr2[0] = 1000
print(arr)
print(arr2)

[1 2 3 4 5]
[3 4]
[1 2 3 4 5]
[1000    4]


2D array

In [18]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
ar[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

2d array


In [20]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:

#3D array (OneS)
tdim=np.ones((2,3,6))
tdim.shape
tdim.size
tdim.ndim

3

MOre function in python

In [37]:
arr=np.arange(1,30,3)
arr

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [38]:
np.random.permutation(arr)

array([ 4, 16, 13, 28, 10,  1, 19,  7, 22, 25])

In [40]:
np.random.randint(10,36)

18

In [41]:
arr=np.random.randn(1000)

In [43]:
import matplotlib.pyplot as plt

plt.hist(arr, bins = 1000)
plt.show()

In [44]:
arr=np.linspace(10,300,100)

In [45]:
arr

array([ 10.        ,  12.92929293,  15.85858586,  18.78787879,
        21.71717172,  24.64646465,  27.57575758,  30.50505051,
        33.43434343,  36.36363636,  39.29292929,  42.22222222,
        45.15151515,  48.08080808,  51.01010101,  53.93939394,
        56.86868687,  59.7979798 ,  62.72727273,  65.65656566,
        68.58585859,  71.51515152,  74.44444444,  77.37373737,
        80.3030303 ,  83.23232323,  86.16161616,  89.09090909,
        92.02020202,  94.94949495,  97.87878788, 100.80808081,
       103.73737374, 106.66666667, 109.5959596 , 112.52525253,
       115.45454545, 118.38383838, 121.31313131, 124.24242424,
       127.17171717, 130.1010101 , 133.03030303, 135.95959596,
       138.88888889, 141.81818182, 144.74747475, 147.67676768,
       150.60606061, 153.53535354, 156.46464646, 159.39393939,
       162.32323232, 165.25252525, 168.18181818, 171.11111111,
       174.04040404, 176.96969697, 179.8989899 , 182.82828283,
       185.75757576, 188.68686869, 191.61616162, 194.54

In [46]:
arr.size

100

In [47]:
print(arr[6]-arr[5])
print(arr[40]-arr[39])

2.929292929292931
2.9292929292929273


In [50]:
arr=np.array([True,False,True,False,True,False])

In [52]:
np.where(arr,100,-100)

array([ 100, -100,  100, -100,  100, -100])

In [54]:
arr=np.arange(1,30)

In [56]:
np.where(arr<5,True,False)

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])